dist: xenial
language: python
notifications:
  email: false
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install poetry
  - poetry install 
script:
  # run the test suite
  - poetry run python -m pytest --cov=src/ --flake8
  # submit the coverage
  - poetry run coveralls
